PrismarineJS/prismarine-viewer

.github/workflows/ci.yml
.gitpod.dockerfile
.gitpod.yml
index.js
jest-puppeteer.config.js
jest.config.js
package.json
readme.md
src/entities.js
test/parallel.js
test/simple.test.js
test/viewer.test.js

start puppeteer testing

---

readme.md

add image to readme

---

.github/workflows/ci.yml

https://docs.github.com/en/actions/reference/context-and-expression-syntax-for-github-actions

deploy only in master

---

lib/mineflayer.js
readme.md
src/index.js
test/viewer.test.js

improve rendering

---

public/index.html

There was some extra whitespace around the canvas and a scrollbar.
This PR fixes the CSS so the viewport should cleanly fill the browser window. Looks much better in my opinion. ^^

Removed Whitespace around Canvas

---

lib/mineflayer.js
package.json

will add new mineflayer version in this PR

remove usage of _columns

---

.github/workflows/ci.yml
examples/headless.js
examples/python/receiver.py
examples/python/sender.js
index.js
lib/atlas.js
lib/headless.js
lib/mineflayer.js
lib/utils.js
package.json
src/index.js
src/models.js
src/worker.js
src/worldrenderer.js

This could be used for ML or interface with other languages.
TODO:
Open questions:
* Should we split pviewer ? There is now 3 different "versions" (standalone, mineflayer, headless) with distinct use cases, does it makes sense to separate them in multiple packages ?
* Should we drop puppeteer in favor of the headless version ? It would be more lightweight but would not test exactly the browser based versions

Proof of concept headless renderer

---

package.json
src/worldrenderer.js

Fix #63
Waiting confirmation, I'll add a minor release commit to this PR.

Fix worker path

---

examples/clickmove.js
lib/mineflayer.js
src/index.js

Closes https://github.com/PrismarineJS/prismarine-viewer/issues/39

Add blockClicked event

---

examples/clickmove.js
examples/proxy.js
src/primitives.js

* Add a proxy example, allowing to display a player current area
* Improve move click so it display the pathfinder planned path

More examples

---

.gitignore
examples/electron/client/app.css
examples/electron/client/bootstrap.js
examples/electron/client/index.html
examples/electron/client/localViewer.js
examples/electron/client/mineflayerViewer.js
examples/electron/client/preload.js
examples/electron/client/remoteViewer.js
examples/electron/client/remoteViewer2x2.js
examples/electron/client/stats.js
examples/electron/client/worker.js
examples/electron/index.js
examples/electron/package.json
lib/worldView.js
src/utils.electron.js
src/worldrenderer.js

Electron demo

---

viewer/lib/models.js

This fix the weird stairs rotations.

Fix rotations

---

viewer/lib/worldView.js

that makes it possible to avoid blocking the main thread when loading chunks

make init and updatePosition non blocking

---

.gitignore
examples/standalone/webpack.config.js
webpack.config.js

we could use both dev and prod mode by having 2 files as advised by https://webpack.js.org/guides/production/
but for now let's keep it simple and just use production

use production mode for webpack for optimizations

---

viewer/lib/worldView.js

gives the opportunity to the mesher to render more sections at once, overall faster

load chunks in slices/batch instead of one by one

---

examples/web_client/.gitignore
examples/web_client/.npmrc
examples/web_client/README.md
examples/web_client/dns.js
examples/web_client/index.html
examples/web_client/index.js
examples/web_client/package.json
examples/web_client/perf_hooks_replacement.js
examples/web_client/server.js
examples/web_client/webpack.config.js

mostly based on https://github.com/Heath123/mineflayer-web-test
@Heath123
@Karang

Add web client example

---

HISTORY.md
lib/mineflayer.js
package.json
readme.md

Add viewer.close()

---

viewer/lib/worldView.js

Small fix to have all versions rendering some entity models

Fix entity name matching on older versions

---

lib/mineflayer.js

Fix bug for draw more than 1 box

Fix drawBoxGrid

---

viewer/lib/models.js

This reverts commit e8f439f603fa60e4a3e3bbc6c99195b5b7fe35e5.
Trying to fix #156

Revert "Improve water rendering"

---

viewer/lib/entities.js
viewer/lib/worldView.js

possible now that mineflayer fixed it

use entity name

---

.github/workflows/ci.yml
.gitignore
.gitpod.dockerfile
index.js
package.json

This PR adds 1.17.1 support.
**Note that I ask that this PR isn't squashed, because the three commits added here all do separate things; it's just that to get 1.17.1 support I have to do the other changes to make it properly work on my local machine and Gitpod.**

1.17.1 Support

---

viewer/lib/entities.js
viewer/lib/primitives.js
viewer/lib/worldrenderer.js

Fixes a few memory leaks

---

examples/headless.js

Update headless example to warn on missing dep

---

examples/standalone/webpack.config.js
webpack.config.js

2-3x smaller bundle size
76MB -> 37MB index.js
75MB -> 22MB worker.js

Remove unused mc-data from bundle

---

viewer/lib/dispose.js

Simplify dispose.js

---

examples/twitch.js

update link to twitch ingest list
